# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    background_image:
      image:
      alt:
    heading:
    lead:
    body:
    ctas:
  config:
    is_main: false
    id:
    aria_labelledby:
  layout:
    is_fluid: false
    width:
    align: left
    vertical_space: py-8
  styles:
    vibe: Down to Business 1
    background_color: bg-dark
    background_blend_mode: Normal
    text_color: text-white
    heading_color: text-white
    ctas: buttons

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_color:
    type: color
    options:
      allow_empty: false
      values:
        - name: Dark
          value: bg-dark
        - name: WVU Gold
          value: bg-wvu-gold
  vibe:
    type: select
    options:
      allow_empty: false
      values:
        - name: WVU Experience 1
          id: wvu-experience-1
        - name: Down to Business 1
          id: down-to-business-1
        - name: Discovery 1
          id: discovery-1
        - name: Nostalgic 1
          id: nostalgic-1
